before_script:
    - apt-get update -qq && apt-get install -y -qq python-dev python-pip texlive
    - pip install -r requirements.txt

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  script:
    - python render.py
  artifacts:
    paths:
    - public
  only:
  - master
